version: "3.9"

services:
  app:
    build: .
    container_name: library-api-app
    ports:
      - "8080:8080"
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: project1
      DB_USERNAME: root
      DB_PASSWORD: example
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: library-api-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: project1
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
